### ISSUE TITLE
.stl Models Huge in Size

### ISSUE THREAD

**Issue by pqpxo** [benhoad/lego-hogwarts-express-iot#1]
Hi there, 

I've attempted to open the .stl files within Chitubox and (sadly to say) Microsoft 3D Builder and all appear to be huge in size when opened/imported. 

Could you confirm the correct sizes for each or fix/investigate the existing .stl files?

Many thanks!

**Comment by benhoad** [comment]
Edit---

I forgot (since it's been 2 years since I touched this last) the train track mesh I used to reference the charging plate design was 10x the size it should've been, the train belly plate is 1:1, but the charging section needs to be scaled down to 10%

**Comment by benhoad** [comment]
Oh do you mean physically huge in size? like it's 10x what it should be?

**Comment by pqpxo** [comment]
> 

Hi Ben,

Yes! 

Did a measurment in Microsoft 3D Builder and it the object was 108cm in width

![exp1](https://user-images.githubusercontent.com/43624115/147986324-0f60b1c3-31d6-46be-a2be-5c5c9ecfba21.jpg)

The blue outline below shows my build space area (Using ELEGOO Mars 2 Pro)

![exp2](https://user-images.githubusercontent.com/43624115/147986327-85b48b25-3f6b-4ff1-ad97-d9155b03c110.jpg)

**Comment by benhoad** [comment]
Yeah with any luck the 10% scale is still not too big that it should fit in your print area.
